package com.springboot.mapper;

import com.springboot.entity.Banner;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface BannerMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table banner
	 *
	 * @mbggenerated Mon Jan 28 11:48:50 CST 2019
	 */
	@Delete({ "delete from banner", "where id = #{id,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table banner
	 *
	 * @mbggenerated Mon Jan 28 11:48:50 CST 2019
	 */
	@Insert({ "insert into banner (id, image, ", "is_show, is_top, title, ", "link_url, create_date, ",
			"update_date, create_by, ", "update_by)", "values (#{id,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, ",
			"#{isShow,jdbcType=VARCHAR}, #{isTop,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
			"#{linkUrl,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
			"#{updateDate,jdbcType=TIMESTAMP}, #{createBy,jdbcType=VARCHAR}, ", "#{updateBy,jdbcType=VARCHAR})" })
	int insert(Banner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table banner
	 *
	 * @mbggenerated Mon Jan 28 11:48:50 CST 2019
	 */
	@Select({ "select", "id, image, is_show, is_top, title, link_url, create_date, update_date, create_by, ",
			"update_by", "from banner", "where id = #{id,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "image", property = "image", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_show", property = "isShow", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_top", property = "isTop", jdbcType = JdbcType.VARCHAR),
			@Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
			@Result(column = "link_url", property = "linkUrl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "create_by", property = "createBy", jdbcType = JdbcType.VARCHAR),
			@Result(column = "update_by", property = "updateBy", jdbcType = JdbcType.VARCHAR) })
	Banner selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table banner
	 *
	 * @mbggenerated Mon Jan 28 11:48:50 CST 2019
	 */
	@Select({ "select", "id, image, is_show, is_top, title, link_url, create_date, update_date, create_by, ",
			"update_by", "from banner" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "image", property = "image", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_show", property = "isShow", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_top", property = "isTop", jdbcType = JdbcType.VARCHAR),
			@Result(column = "title", property = "title", jdbcType = JdbcType.VARCHAR),
			@Result(column = "link_url", property = "linkUrl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "create_by", property = "createBy", jdbcType = JdbcType.VARCHAR),
			@Result(column = "update_by", property = "updateBy", jdbcType = JdbcType.VARCHAR) })
	List<Banner> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table banner
	 *
	 * @mbggenerated Mon Jan 28 11:48:50 CST 2019
	 */
	@Update({ "update banner", "set image = #{image,jdbcType=VARCHAR},", "is_show = #{isShow,jdbcType=VARCHAR},",
			"is_top = #{isTop,jdbcType=VARCHAR},", "title = #{title,jdbcType=VARCHAR},",
			"link_url = #{linkUrl,jdbcType=VARCHAR},", "create_date = #{createDate,jdbcType=TIMESTAMP},",
			"update_date = #{updateDate,jdbcType=TIMESTAMP},", "create_by = #{createBy,jdbcType=VARCHAR},",
			"update_by = #{updateBy,jdbcType=VARCHAR}", "where id = #{id,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(Banner record);

	@SelectProvider(type = com.springboot.entity.dyna.BannerDynaProvider.class, method = "selectProvider")
	List<Banner> findList(Map<String, Object> map);

	@UpdateProvider(type = com.springboot.entity.dyna.BannerDynaProvider.class, method = "updateProvider")
	int update(Map<String, Object> map);
}