package com.springboot.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.springboot.entity.OrderItem;

@Mapper
public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Mon Mar 18 22:07:52 CST 2019
     */
    @Delete({
        "delete from t_order_item",
        "where order_item_id = #{orderItemId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Mon Mar 18 22:07:52 CST 2019
     */
    @Insert({
        "insert into t_order_item (order_item_id, userid, ",
        "sellid, create_time, ",
        "status, productid, ",
        "quantity, payment, ",
        "update_time, confirm_time, ",
        "price, order_id, address_id)",
        "values (#{orderItemId,jdbcType=VARCHAR}, #{userid,jdbcType=VARCHAR}, ",
        "#{sellid,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=VARCHAR}, #{productid,jdbcType=VARCHAR}, ",
        "#{quantity,jdbcType=INTEGER}, #{payment,jdbcType=DOUBLE}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{confirmTime,jdbcType=TIMESTAMP}, ",
        "#{price,jdbcType=DOUBLE}, #{orderId,jdbcType=VARCHAR}, #{addressId,jdbcType=VARCHAR})"
    })
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Mon Mar 18 22:07:52 CST 2019
     */
    @Select({
        "select",
        "order_item_id, userid, sellid, create_time, status, productid, quantity, payment, ",
        "update_time, confirm_time, price, order_id, address_id",
        "from t_order_item",
        "where order_item_id = #{orderItemId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="sellid", property="sellid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="productid", property="productid", jdbcType=JdbcType.VARCHAR),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="payment", property="payment", jdbcType=JdbcType.DOUBLE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="confirm_time", property="confirmTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.VARCHAR)
    })
    OrderItem selectByPrimaryKey(String orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Mon Mar 18 22:07:52 CST 2019
     */
    @Select({
        "select",
        "order_item_id, userid, sellid, create_time, status, productid, quantity, payment, ",
        "update_time, confirm_time, price, order_id, address_id",
        "from t_order_item"
    })
    @Results({
        @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="sellid", property="sellid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="productid", property="productid", jdbcType=JdbcType.VARCHAR),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="payment", property="payment", jdbcType=JdbcType.DOUBLE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="confirm_time", property="confirmTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.VARCHAR)
    })
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Mon Mar 18 22:07:52 CST 2019
     */
    @Update({
        "update t_order_item",
        "set userid = #{userid,jdbcType=VARCHAR},",
          "sellid = #{sellid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=VARCHAR},",
          "productid = #{productid,jdbcType=VARCHAR},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "payment = #{payment,jdbcType=DOUBLE},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "confirm_time = #{confirmTime,jdbcType=TIMESTAMP},",
          "price = #{price,jdbcType=DOUBLE},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "address_id = #{addressId,jdbcType=VARCHAR}",
        "where order_item_id = #{orderItemId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OrderItem record);
    
    @SelectProvider(type = com.springboot.entity.dyna.OrderItemDynaProvider.class, method = "selectProvider")
	@Results({
        @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="sellid", property="sellid", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="productid", property="productid", jdbcType=JdbcType.VARCHAR),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="payment", property="payment", jdbcType=JdbcType.DOUBLE),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="confirm_time", property="confirmTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="address_id", property="addressId", jdbcType=JdbcType.VARCHAR)
    })
	List<OrderItem> findList(Map<String, Object> map);

	@SelectProvider(type = com.springboot.entity.dyna.OrderItemDynaProvider.class, method = "updateProvider")
	Integer update(Map<String, Object> map);

	// 连表查询
	@SelectProvider(type = com.springboot.entity.dyna.OrderItemDynaProvider.class, method = "selectBySql")
	@Results({ 
		@Result(column = "order_id", property = "orderId", jdbcType = JdbcType.VARCHAR, id = true),
		 @Result(column="order_item_id", property="orderItemId", jdbcType=JdbcType.VARCHAR, id=true),
		@Result(column = "create_time", property = "create_time", jdbcType = JdbcType.TIMESTAMP),
		@Result(column = "quantity", property = "quantity", jdbcType = JdbcType.INTEGER),
		@Result(column = "payment", property = "payment", jdbcType = JdbcType.DOUBLE),
		@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
		@Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
		@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
		@Result(column = "price", property = "price", jdbcType = JdbcType.DOUBLE),
		@Result(column = "isNotAuction", property = "isnotauction", jdbcType = JdbcType.VARCHAR),
		@Result(column = "proid", property = "proid", jdbcType = JdbcType.VARCHAR),
		@Result(column = "img", property = "img", jdbcType = JdbcType.VARCHAR),
		@Result(column = "addrid", property = "addrid", jdbcType = JdbcType.VARCHAR, id = true),
		@Result(column = "userid", property = "userid", jdbcType = JdbcType.VARCHAR),
		@Result(column = "sellid", property = "sellid", jdbcType = JdbcType.VARCHAR),
		@Result(column = "province", property = "province", jdbcType = JdbcType.VARCHAR),
		@Result(column = "city", property = "city", jdbcType = JdbcType.VARCHAR),
		@Result(column = "region", property = "region", jdbcType = JdbcType.VARCHAR),
		@Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
		@Result(column = "postal", property = "postal", jdbcType = JdbcType.VARCHAR),
		@Result(column = "consignee", property = "consignee", jdbcType = JdbcType.VARCHAR)
	})
	List<Map<String, Object>> findListBy(Map<String, Object> map);
	
  	@Select({
        "select count(1) count from T_ORDER_ITEM o",
        "where date_format(o.CREATE_TIME,'%Y-%m')=#{date}",
        "group by date_format(o.CREATE_TIME,'%Y-%m')",
        "order by date_format(o.CREATE_TIME,'%Y-%m')"
    })
  	@Results({
        @Result(column="count", property="count", jdbcType=JdbcType.BIGINT)
    })
	Integer getMonth(String date);
}