package com.springboot.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import com.springboot.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    @Insert({
        "insert into user (id, username, ",
        "password, gender, ",
        "img, create_time, ",
        "state, loginName, ",
        "activeCode, activeDate, ",
        "adreess, tel, lastLoginTime, ",
        "email)",
        "values (#{id,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{gender,jdbcType=VARCHAR}, ",
        "#{img,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{state,jdbcType=VARCHAR}, #{loginname,jdbcType=VARCHAR}, ",
        "#{activecode,jdbcType=VARCHAR}, #{activedate,jdbcType=TIMESTAMP}, ",
        "#{adreess,jdbcType=VARCHAR}, #{tel,jdbcType=VARCHAR}, #{lastlogintime,jdbcType=TIMESTAMP}, ",
        "#{email,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    @Select({
        "select",
        "id, username, password, gender, img, create_time, state, loginName, activeCode, ",
        "activeDate, adreess, tel, lastLoginTime, email",
        "from user",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="loginName", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeCode", property="activecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeDate", property="activedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="adreess", property="adreess", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastLoginTime", property="lastlogintime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    @Select({
        "select",
        "id, username, password, gender, img, create_time, state, loginName, activeCode, ",
        "activeDate, adreess, tel, lastLoginTime, email",
        "from user"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="loginName", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeCode", property="activecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeDate", property="activedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="adreess", property="adreess", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastLoginTime", property="lastlogintime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    @Update({
        "update user",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "gender = #{gender,jdbcType=VARCHAR},",
          "img = #{img,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "state = #{state,jdbcType=VARCHAR},",
          "loginName = #{loginname,jdbcType=VARCHAR},",
          "activeCode = #{activecode,jdbcType=VARCHAR},",
          "activeDate = #{activedate,jdbcType=TIMESTAMP},",
          "adreess = #{adreess,jdbcType=VARCHAR},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "lastLoginTime = #{lastlogintime,jdbcType=TIMESTAMP},",
          "email = #{email,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
    
    @SelectProvider(type = com.springboot.entity.dyna.UserDynaProvider.class, method = "selectProvider")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="gender", property="gender", jdbcType=JdbcType.VARCHAR),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="state", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="loginName", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeCode", property="activecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="activeDate", property="activedate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="adreess", property="adreess", jdbcType=JdbcType.VARCHAR),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="lastLoginTime", property="lastlogintime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    List<User> findList(Map<String, Object> map);
    
    @SelectProvider(type = com.springboot.entity.dyna.UserDynaProvider.class, method = "updateProvider")
    int update(Map<String, Object> map);
}