package com.springboot.entity;

import java.util.Date;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addrid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String addrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.region
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.postal
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String postal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.consignee
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.status
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.createdate
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addrid
     *
     * @return the value of address.addrid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getAddrid() {
        return addrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addrid
     *
     * @param addrid the value for address.addrid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setAddrid(String addrid) {
        this.addrid = addrid == null ? null : addrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userid
     *
     * @return the value of address.userid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userid
     *
     * @param userid the value for address.userid
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.region
     *
     * @return the value of address.region
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.region
     *
     * @param region the value for address.region
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.postal
     *
     * @return the value of address.postal
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getPostal() {
        return postal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.postal
     *
     * @param postal the value for address.postal
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setPostal(String postal) {
        this.postal = postal == null ? null : postal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.consignee
     *
     * @return the value of address.consignee
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.consignee
     *
     * @param consignee the value for address.consignee
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.status
     *
     * @return the value of address.status
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.status
     *
     * @param status the value for address.status
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.createdate
     *
     * @return the value of address.createdate
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.createdate
     *
     * @param createdate the value for address.createdate
     *
     * @mbg.generated Sun Nov 25 17:20:28 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}