package com.springboot.entity;

import java.util.Date;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.addrid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String addrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.userid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.region
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.postal
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String postal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.consignee
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.status
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.createdate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.addrid
     *
     * @return the value of t_address.addrid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getAddrid() {
        return addrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.addrid
     *
     * @param addrid the value for t_address.addrid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setAddrid(String addrid) {
        this.addrid = addrid == null ? null : addrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.userid
     *
     * @return the value of t_address.userid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.userid
     *
     * @param userid the value for t_address.userid
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.province
     *
     * @return the value of t_address.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.province
     *
     * @param province the value for t_address.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.city
     *
     * @return the value of t_address.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.city
     *
     * @param city the value for t_address.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.region
     *
     * @return the value of t_address.region
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.region
     *
     * @param region the value for t_address.region
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address
     *
     * @return the value of t_address.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address
     *
     * @param address the value for t_address.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.postal
     *
     * @return the value of t_address.postal
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getPostal() {
        return postal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.postal
     *
     * @param postal the value for t_address.postal
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setPostal(String postal) {
        this.postal = postal == null ? null : postal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.consignee
     *
     * @return the value of t_address.consignee
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.consignee
     *
     * @param consignee the value for t_address.consignee
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.phone
     *
     * @return the value of t_address.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.phone
     *
     * @param phone the value for t_address.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.status
     *
     * @return the value of t_address.status
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.status
     *
     * @param status the value for t_address.status
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.createdate
     *
     * @return the value of t_address.createdate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.createdate
     *
     * @param createdate the value for t_address.createdate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}