package com.springboot.entity;

import java.util.Date;

public class Banner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.image
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.is_show
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.is_top
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.title
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.link_url
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.create_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.update_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.create_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_banner.update_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.id
     *
     * @return the value of t_banner.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.id
     *
     * @param id the value for t_banner.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.image
     *
     * @return the value of t_banner.image
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.image
     *
     * @param image the value for t_banner.image
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.is_show
     *
     * @return the value of t_banner.is_show
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.is_show
     *
     * @param isShow the value for t_banner.is_show
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.is_top
     *
     * @return the value of t_banner.is_top
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.is_top
     *
     * @param isTop the value for t_banner.is_top
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setIsTop(String isTop) {
        this.isTop = isTop == null ? null : isTop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.title
     *
     * @return the value of t_banner.title
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.title
     *
     * @param title the value for t_banner.title
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.link_url
     *
     * @return the value of t_banner.link_url
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.link_url
     *
     * @param linkUrl the value for t_banner.link_url
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.create_date
     *
     * @return the value of t_banner.create_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.create_date
     *
     * @param createDate the value for t_banner.create_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.update_date
     *
     * @return the value of t_banner.update_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.update_date
     *
     * @param updateDate the value for t_banner.update_date
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.create_by
     *
     * @return the value of t_banner.create_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.create_by
     *
     * @param createBy the value for t_banner.create_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_banner.update_by
     *
     * @return the value of t_banner.update_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_banner.update_by
     *
     * @param updateBy the value for t_banner.update_by
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}