package com.springboot.entity;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.sub
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String sub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.createdate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.updatedate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.createby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.updateby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.istop
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    private String istop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.sub
     *
     * @return the value of news.sub
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getSub() {
        return sub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.sub
     *
     * @param sub the value for news.sub
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setSub(String sub) {
        this.sub = sub == null ? null : sub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.createdate
     *
     * @return the value of news.createdate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.createdate
     *
     * @param createdate the value for news.createdate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.updatedate
     *
     * @return the value of news.updatedate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.updatedate
     *
     * @param updatedate the value for news.updatedate
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.createby
     *
     * @return the value of news.createby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.createby
     *
     * @param createby the value for news.createby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.updateby
     *
     * @return the value of news.updateby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.updateby
     *
     * @param updateby the value for news.updateby
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.istop
     *
     * @return the value of news.istop
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public String getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.istop
     *
     * @param istop the value for news.istop
     *
     * @mbggenerated Wed Mar 06 14:24:52 CST 2019
     */
    public void setIstop(String istop) {
        this.istop = istop == null ? null : istop.trim();
    }
}