package com.springboot.entity;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.addr_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String addrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.payment
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Double payment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.addr_id
     *
     * @return the value of t_order.addr_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.addr_id
     *
     * @param addrId the value for t_order.addr_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setAddrId(String addrId) {
        this.addrId = addrId == null ? null : addrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.payment
     *
     * @return the value of t_order.payment
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Double getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.payment
     *
     * @param payment the value for t_order.payment
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setPayment(Double payment) {
        this.payment = payment;
    }
}