package com.springboot.entity;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sellid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String sellid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.createdate
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userid
     *
     * @return the value of order.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userid
     *
     * @param userid the value for order.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sellid
     *
     * @return the value of order.sellid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getSellid() {
        return sellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sellid
     *
     * @param sellid the value for order.sellid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setSellid(String sellid) {
        this.sellid = sellid == null ? null : sellid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.createdate
     *
     * @return the value of order.createdate
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.createdate
     *
     * @param createdate the value for order.createdate
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}