package com.springboot.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createdate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updatedate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updateby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.userid
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.hits
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Integer hits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.minprice
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Float minprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.faver
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    private Integer faver;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createdate
     *
     * @return the value of product.createdate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createdate
     *
     * @param createdate the value for product.createdate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updatedate
     *
     * @return the value of product.updatedate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updatedate
     *
     * @param updatedate the value for product.updatedate
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createby
     *
     * @return the value of product.createby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createby
     *
     * @param createby the value for product.createby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updateby
     *
     * @return the value of product.updateby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updateby
     *
     * @param updateby the value for product.updateby
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img
     *
     * @return the value of product.img
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img
     *
     * @param img the value for product.img
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.userid
     *
     * @return the value of product.userid
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.userid
     *
     * @param userid the value for product.userid
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.hits
     *
     * @return the value of product.hits
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.hits
     *
     * @param hits the value for product.hits
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.minprice
     *
     * @return the value of product.minprice
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Float getMinprice() {
        return minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.minprice
     *
     * @param minprice the value for product.minprice
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setMinprice(Float minprice) {
        this.minprice = minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.faver
     *
     * @return the value of product.faver
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public Integer getFaver() {
        return faver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.faver
     *
     * @param faver the value for product.faver
     *
     * @mbggenerated Tue Nov 06 14:26:28 CST 2018
     */
    public void setFaver(Integer faver) {
        this.faver = faver;
    }
}