package com.springboot.entity;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createdate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updatedate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updateby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.userid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.hits
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Integer hits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.min_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Float minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.faver
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Integer faver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.status
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sellpoint
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String sellpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.max_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Float maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.quality
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Integer quality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.isNotAuction
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String isnotauction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.increments
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private Float increments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.currentBidder
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String currentbidder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.bidderId
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String bidderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.outTime
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.auctionStatus
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    private String auctionstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proid
     *
     * @return the value of product.proid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proid
     *
     * @param proid the value for product.proid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail
     *
     * @return the value of product.detail
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail
     *
     * @param detail the value for product.detail
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createdate
     *
     * @return the value of product.createdate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createdate
     *
     * @param createdate the value for product.createdate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updatedate
     *
     * @return the value of product.updatedate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updatedate
     *
     * @param updatedate the value for product.updatedate
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createby
     *
     * @return the value of product.createby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createby
     *
     * @param createby the value for product.createby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updateby
     *
     * @return the value of product.updateby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updateby
     *
     * @param updateby the value for product.updateby
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img
     *
     * @return the value of product.img
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img
     *
     * @param img the value for product.img
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.userid
     *
     * @return the value of product.userid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.userid
     *
     * @param userid the value for product.userid
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.hits
     *
     * @return the value of product.hits
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.hits
     *
     * @param hits the value for product.hits
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.min_price
     *
     * @return the value of product.min_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Float getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.min_price
     *
     * @param minPrice the value for product.min_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setMinPrice(Float minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.faver
     *
     * @return the value of product.faver
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Integer getFaver() {
        return faver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.faver
     *
     * @param faver the value for product.faver
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setFaver(Integer faver) {
        this.faver = faver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.status
     *
     * @return the value of product.status
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.status
     *
     * @param status the value for product.status
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sellpoint
     *
     * @return the value of product.sellpoint
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getSellpoint() {
        return sellpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sellpoint
     *
     * @param sellpoint the value for product.sellpoint
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setSellpoint(String sellpoint) {
        this.sellpoint = sellpoint == null ? null : sellpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.max_price
     *
     * @return the value of product.max_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Float getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.max_price
     *
     * @param maxPrice the value for product.max_price
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setMaxPrice(Float maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.quality
     *
     * @return the value of product.quality
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Integer getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.quality
     *
     * @param quality the value for product.quality
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setQuality(Integer quality) {
        this.quality = quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.isNotAuction
     *
     * @return the value of product.isNotAuction
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getIsnotauction() {
        return isnotauction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.isNotAuction
     *
     * @param isnotauction the value for product.isNotAuction
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setIsnotauction(String isnotauction) {
        this.isnotauction = isnotauction == null ? null : isnotauction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.increments
     *
     * @return the value of product.increments
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public Float getIncrements() {
        return increments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.increments
     *
     * @param increments the value for product.increments
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setIncrements(Float increments) {
        this.increments = increments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.currentBidder
     *
     * @return the value of product.currentBidder
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getCurrentbidder() {
        return currentbidder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.currentBidder
     *
     * @param currentbidder the value for product.currentBidder
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setCurrentbidder(String currentbidder) {
        this.currentbidder = currentbidder == null ? null : currentbidder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.bidderId
     *
     * @return the value of product.bidderId
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getBidderid() {
        return bidderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.bidderId
     *
     * @param bidderid the value for product.bidderId
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setBidderid(String bidderid) {
        this.bidderid = bidderid == null ? null : bidderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.outTime
     *
     * @return the value of product.outTime
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.outTime
     *
     * @param outtime the value for product.outTime
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setOuttime(String outtime) {
        this.outtime = outtime == null ? null : outtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.auctionStatus
     *
     * @return the value of product.auctionStatus
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public String getAuctionstatus() {
        return auctionstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.auctionStatus
     *
     * @param auctionstatus the value for product.auctionStatus
     *
     * @mbggenerated Fri Mar 01 09:18:56 CST 2019
     */
    public void setAuctionstatus(String auctionstatus) {
        this.auctionstatus = auctionstatus == null ? null : auctionstatus.trim();
    }
}