package com.springboot.entity;

public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.quantity
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.total
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private Float total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.productid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.ischeck
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    private String ischeck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.id
     *
     * @return the value of shoppingcart.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.id
     *
     * @param id the value for shoppingcart.id
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.userid
     *
     * @return the value of shoppingcart.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.userid
     *
     * @param userid the value for shoppingcart.userid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.quantity
     *
     * @return the value of shoppingcart.quantity
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.quantity
     *
     * @param quantity the value for shoppingcart.quantity
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.total
     *
     * @return the value of shoppingcart.total
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.total
     *
     * @param total the value for shoppingcart.total
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.productid
     *
     * @return the value of shoppingcart.productid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.productid
     *
     * @param productid the value for shoppingcart.productid
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.ischeck
     *
     * @return the value of shoppingcart.ischeck
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public String getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.ischeck
     *
     * @param ischeck the value for shoppingcart.ischeck
     *
     * @mbg.generated Sun Nov 18 20:45:59 CST 2018
     */
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck == null ? null : ischeck.trim();
    }
}