package com.springboot.entity;

import java.util.Date;

public class ShoppingCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.cartid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private String cartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.userid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.quantity
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.total
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.productid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.createdate
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcart.ischeck
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    private String ischeck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.cartid
     *
     * @return the value of shoppingcart.cartid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public String getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.cartid
     *
     * @param cartid the value for shoppingcart.cartid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setCartid(String cartid) {
        this.cartid = cartid == null ? null : cartid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.userid
     *
     * @return the value of shoppingcart.userid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.userid
     *
     * @param userid the value for shoppingcart.userid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.quantity
     *
     * @return the value of shoppingcart.quantity
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.quantity
     *
     * @param quantity the value for shoppingcart.quantity
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.total
     *
     * @return the value of shoppingcart.total
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.total
     *
     * @param total the value for shoppingcart.total
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.productid
     *
     * @return the value of shoppingcart.productid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.productid
     *
     * @param productid the value for shoppingcart.productid
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.createdate
     *
     * @return the value of shoppingcart.createdate
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.createdate
     *
     * @param createdate the value for shoppingcart.createdate
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcart.ischeck
     *
     * @return the value of shoppingcart.ischeck
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public String getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcart.ischeck
     *
     * @param ischeck the value for shoppingcart.ischeck
     *
     * @mbggenerated Wed Nov 21 11:12:59 CST 2018
     */
    public void setIscheck(String ischeck) {
        this.ischeck = ischeck == null ? null : ischeck.trim();
    }
}