package com.springboot.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.gender
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.img
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.state
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.loginname
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.usertype
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.activeCode
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String activecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.activeDate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date activedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.adreess
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String adreess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastLoginTime
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.area
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    private String area;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.gender
     *
     * @return the value of t_user.gender
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.gender
     *
     * @param gender the value for t_user.gender
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.img
     *
     * @return the value of t_user.img
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.img
     *
     * @param img the value for t_user.img
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.state
     *
     * @return the value of t_user.state
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.state
     *
     * @param state the value for t_user.state
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.loginname
     *
     * @return the value of t_user.loginname
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.loginname
     *
     * @param loginname the value for t_user.loginname
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.usertype
     *
     * @return the value of t_user.usertype
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.usertype
     *
     * @param usertype the value for t_user.usertype
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.activeCode
     *
     * @return the value of t_user.activeCode
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getActivecode() {
        return activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.activeCode
     *
     * @param activecode the value for t_user.activeCode
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setActivecode(String activecode) {
        this.activecode = activecode == null ? null : activecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.activeDate
     *
     * @return the value of t_user.activeDate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getActivedate() {
        return activedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.activeDate
     *
     * @param activedate the value for t_user.activeDate
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setActivedate(Date activedate) {
        this.activedate = activedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.adreess
     *
     * @return the value of t_user.adreess
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getAdreess() {
        return adreess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.adreess
     *
     * @param adreess the value for t_user.adreess
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setAdreess(String adreess) {
        this.adreess = adreess == null ? null : adreess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastLoginTime
     *
     * @return the value of t_user.lastLoginTime
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastLoginTime
     *
     * @param lastlogintime the value for t_user.lastLoginTime
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.province
     *
     * @return the value of t_user.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.province
     *
     * @param province the value for t_user.province
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.city
     *
     * @return the value of t_user.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.city
     *
     * @param city the value for t_user.city
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.area
     *
     * @return the value of t_user.area
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.area
     *
     * @param area the value for t_user.area
     *
     * @mbggenerated Thu Mar 14 09:08:27 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }
}